#!/bin/bash

# A demonstration of '/proc/stat' with json output

# A simple aesthetic function to give another name for '.'
# shellcheck disable=SC1090
include() { . "${1}" || exit 1; }

include ../lib/jsonprint.sh

json_require /proc/stat

json_open
  json_open_obj /proc/stat
    while read -r; do
      # We want word splitting here
      # shellcheck disable=SC2086
      set -- ${REPLY}
      case "${1}" in
        ('cpu')
          json_foreach --name "${1}" user "${2}" nice "${3}" system "${4}" \
            idle "${5}" iowait "${6}" irq "${7}" softirq "${8}" steal "${9}" \
            guest "${10}" guest_nice "${11}"
        ;;
        (cpu*)
          json_comma
          json_foreach --name "${1}" user "${2}" nice "${3}" system "${4}" \
            idle "${5}" iowait "${6}" irq "${7}" softirq "${8}" steal "${9}" \
            guest "${10}" guest_nice "${11}"
        ;;
        (^disk_io|^softirq)
          # We don't want this information, so we no-op
          :
        ;;
        (*)
          json_append_num "${1}" "${2}"
        ;;
      esac
    done < /proc/stat
  json_close_obj
  json_timestamp
json_close