#!/bin/bash

# A demonstration of '/etc/passwd' with json output

# A simple aesthetic function to give another name for '.'
# shellcheck disable=SC1090
include() { . "${1}" || exit 1; }

include ../jsonprint.sh

json_require /etc/passwd

mapfile -t passwd_raw < <(grep -v '^[[:space:]]*#' /etc/passwd)

loop_iter=0
element_count="${#passwd_raw[@]}"

json_open
  json_open_arr passwd
    json_open_obj
    for entry in "${passwd_raw[@]}"; do
      IFS=: read -r _username _password _uid _gid _gecos _home _shell <<< "${entry}"
      json_str username "${_username}"
      json_append_num uid "${_uid}"
      json_append_num gid "${_gid}"
      json_append_str gecos "${_gecos}"
      json_append_str home "${_home}"
      json_append_str shell "${_shell}"
      (( loop_iter++ ))
      if (( loop_iter < element_count )); then
        json_append_obj
      else
        json_close_obj
      fi
    done
  json_close_arr
json_close
