#!/bin/bash

# A demonstration of '/etc/hosts' with json output

# A simple aesthetic function to give another name for '.'
# shellcheck disable=SC1090
include() { . "${1}" || exit 1; }

include ../jsonprint.sh

json_require /etc/hosts

# Strip comments and blank lines
mapfile -t hosts_raw < <(grep -v '^[[:space:]]*#' /etc/hosts | grep -v '^[[:space:]]*$')

loop_iter=0
element_count="${#hosts_raw[@]}"

json_open
  json_open_arr hosts
    json_open_obj
    for entry in "${hosts_raw[@]}"; do
      # shellcheck disable=SC2086
      set -- ${entry}
      _ip="${1}"; shift
      json_str ip "${_ip}"
      json_append_str hostnames "${*}"
      (( loop_iter++ ))
      if (( loop_iter < element_count )); then
        json_append_obj
      else
        json_close_obj
      fi
    done
  json_close_arr
json_close
