#!/bin/bash

source ~/git/sh_libpath/init.sh

include text/case
include text/greet
include text/repeat
include utils/puts

get_greeting
puts Hello world!
str_repeat -n "$(altcaps $(puts Hello world!))" 10

