site_name: Shellac
site_description: The missing library ecosystem for shell
site_url: https://rawiriblundell.github.io/shellac/
repo_url: https://github.com/rawiriblundell/shellac
repo_name: rawiriblundell/shellac
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - toc:
      permalink: true
