site_name: Shellac
site_description: The missing library ecosystem for shell
site_url: https://rawiriblundell.github.io/shellac/
repo_url: https://github.com/rawiriblundell/shellac
repo_name: rawiriblundell/shellac
edit_uri: edit/main/docs/

theme:
  name: simple-blog
  sidebar: true
  navigation_depth: 3
  logo: images/shellac-light.png

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - toc:
      permalink: true
