name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bats:
    name: bats (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats
        run: sudo apt-get install -y bats

      - name: Run tests
        run: bats test/bats/

      - name: Run tests (verbose on failure)
        if: failure()
        run: bats --verbose-run test/bats/
